Repository amoria-global/faxon, pull requests merged in 2025-09, with the labels that each got.

#13 feat: admin management
  prisma/dev.db
  src/config/config.ts
  src/controllers/auth.controller.ts
  src/routes/auth.routes.ts
  src/services/auth.service.ts
  src/types/auth.types.ts
Labels: enhancement, work in progress

#29 KYC-host-tour
  prisma/schema.prisma
  src/controllers/auth.controller.ts
  src/routes/auth.routes.ts
  src/services/auth.service.ts
  src/types/auth.types.ts
  yarn.lock
Labels: enhancement

#34 settings-profile
  prisma/schema.prisma
  src/controllers/auth.controller.ts
  src/controllers/settings.controller.ts
  src/middleware/property.middleware.ts
  src/routes/auth.routes.ts
  src/routes/settings.routes.ts
  src/server.ts
  src/services/auth.service.ts
  src/services/property.service.ts
  src/services/settings.service.ts
  src/types/settings.types.ts
  yarn.lock
Labels: bug
